CREATE TABLE department (
  id BIGINT(20) NOT NULL AUTO_INCREMENT,
    departmentId VARCHAR(24) NULL DEFAULT NULL, departmentName VARCHAR(24) NULL DEFAULT NULL,lastName VARCHAR(24) NULL DEFAULT NULL,
  PRIMARY KEY (id)) 
  